- name: install nginx
  yum: name=nginx state=latest
  when: ansible_os_family == "RedHat"
- name: install conf file
  copy: src=lb.conf dest=/etc/nginx/conf.d/lb.conf
  notify: restart nginx
  tags: conf
- name: start nginx
  service: name=nginx state=started
  
